# Generated by Django 5.2.8 on 2026-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('poster', models.URLField(max_length=1000)),
                ('genres', models.JSONField(default=list)),
                ('vibe', models.CharField(max_length=100)),
                ('intensity', models.IntegerField()),
                ('era', models.CharField(max_length=50)),
            ],
        ),
    ]
